apiVersion: v1
kind: Service
metadata:
  name: nutriport
  labels:
    app: nutriport
    tier: Service
spec:
  type: NodePort
  ports:
  - port: 8085
    nodePort: 31711
  selector:
    app: nutriport