// Code generated by go-swagger; DO NOT EDIT.

package food_item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Nutriport/client/models"
)

// CreateFoodItemReader is a Reader for the CreateFoodItem structure.
type CreateFoodItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFoodItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateFoodItemCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewCreateFoodItemUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateFoodItemInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateFoodItemCreated creates a CreateFoodItemCreated with default headers values
func NewCreateFoodItemCreated() *CreateFoodItemCreated {
	return &CreateFoodItemCreated{}
}

/*CreateFoodItemCreated handles this case with default header values.

A single food item record
*/
type CreateFoodItemCreated struct {
	Payload *models.FoodItem
}

func (o *CreateFoodItemCreated) Error() string {
	return fmt.Sprintf("[POST /fooditem][%d] createFoodItemCreated  %+v", 201, o.Payload)
}

func (o *CreateFoodItemCreated) GetPayload() *models.FoodItem {
	return o.Payload
}

func (o *CreateFoodItemCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FoodItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateFoodItemUnprocessableEntity creates a CreateFoodItemUnprocessableEntity with default headers values
func NewCreateFoodItemUnprocessableEntity() *CreateFoodItemUnprocessableEntity {
	return &CreateFoodItemUnprocessableEntity{}
}

/*CreateFoodItemUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type CreateFoodItemUnprocessableEntity struct {
}

func (o *CreateFoodItemUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /fooditem][%d] createFoodItemUnprocessableEntity ", 422)
}

func (o *CreateFoodItemUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateFoodItemInternalServerError creates a CreateFoodItemInternalServerError with default headers values
func NewCreateFoodItemInternalServerError() *CreateFoodItemInternalServerError {
	return &CreateFoodItemInternalServerError{}
}

/*CreateFoodItemInternalServerError handles this case with default header values.

Internal Server Error
*/
type CreateFoodItemInternalServerError struct {
}

func (o *CreateFoodItemInternalServerError) Error() string {
	return fmt.Sprintf("[POST /fooditem][%d] createFoodItemInternalServerError ", 500)
}

func (o *CreateFoodItemInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
