// Code generated by go-swagger; DO NOT EDIT.

package food_item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Nutriport/client/models"
)

// GetFoodItemByNameReader is a Reader for the GetFoodItemByName structure.
type GetFoodItemByNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFoodItemByNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFoodItemByNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewGetFoodItemByNameUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetFoodItemByNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFoodItemByNameOK creates a GetFoodItemByNameOK with default headers values
func NewGetFoodItemByNameOK() *GetFoodItemByNameOK {
	return &GetFoodItemByNameOK{}
}

/*GetFoodItemByNameOK handles this case with default header values.

A single food item record
*/
type GetFoodItemByNameOK struct {
	Payload *models.FoodItem
}

func (o *GetFoodItemByNameOK) Error() string {
	return fmt.Sprintf("[GET /fooditem/{foodName}][%d] getFoodItemByNameOK  %+v", 200, o.Payload)
}

func (o *GetFoodItemByNameOK) GetPayload() *models.FoodItem {
	return o.Payload
}

func (o *GetFoodItemByNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FoodItem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFoodItemByNameUnprocessableEntity creates a GetFoodItemByNameUnprocessableEntity with default headers values
func NewGetFoodItemByNameUnprocessableEntity() *GetFoodItemByNameUnprocessableEntity {
	return &GetFoodItemByNameUnprocessableEntity{}
}

/*GetFoodItemByNameUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type GetFoodItemByNameUnprocessableEntity struct {
}

func (o *GetFoodItemByNameUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /fooditem/{foodName}][%d] getFoodItemByNameUnprocessableEntity ", 422)
}

func (o *GetFoodItemByNameUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFoodItemByNameInternalServerError creates a GetFoodItemByNameInternalServerError with default headers values
func NewGetFoodItemByNameInternalServerError() *GetFoodItemByNameInternalServerError {
	return &GetFoodItemByNameInternalServerError{}
}

/*GetFoodItemByNameInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetFoodItemByNameInternalServerError struct {
}

func (o *GetFoodItemByNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /fooditem/{foodName}][%d] getFoodItemByNameInternalServerError ", 500)
}

func (o *GetFoodItemByNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
