// Code generated by go-swagger; DO NOT EDIT.

package food_item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAllFoodItemsParams creates a new GetAllFoodItemsParams object
// with the default values initialized.
func NewGetAllFoodItemsParams() *GetAllFoodItemsParams {

	return &GetAllFoodItemsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllFoodItemsParamsWithTimeout creates a new GetAllFoodItemsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllFoodItemsParamsWithTimeout(timeout time.Duration) *GetAllFoodItemsParams {

	return &GetAllFoodItemsParams{

		timeout: timeout,
	}
}

// NewGetAllFoodItemsParamsWithContext creates a new GetAllFoodItemsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllFoodItemsParamsWithContext(ctx context.Context) *GetAllFoodItemsParams {

	return &GetAllFoodItemsParams{

		Context: ctx,
	}
}

// NewGetAllFoodItemsParamsWithHTTPClient creates a new GetAllFoodItemsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllFoodItemsParamsWithHTTPClient(client *http.Client) *GetAllFoodItemsParams {

	return &GetAllFoodItemsParams{
		HTTPClient: client,
	}
}

/*GetAllFoodItemsParams contains all the parameters to send to the API endpoint
for the get all food items operation typically these are written to a http.Request
*/
type GetAllFoodItemsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all food items params
func (o *GetAllFoodItemsParams) WithTimeout(timeout time.Duration) *GetAllFoodItemsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all food items params
func (o *GetAllFoodItemsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all food items params
func (o *GetAllFoodItemsParams) WithContext(ctx context.Context) *GetAllFoodItemsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all food items params
func (o *GetAllFoodItemsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all food items params
func (o *GetAllFoodItemsParams) WithHTTPClient(client *http.Client) *GetAllFoodItemsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all food items params
func (o *GetAllFoodItemsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllFoodItemsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
