// Code generated by go-swagger; DO NOT EDIT.

package food_item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/garcialuis/Nutriport/client/models"
)

// GetAllFoodItemsReader is a Reader for the GetAllFoodItems structure.
type GetAllFoodItemsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAllFoodItemsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAllFoodItemsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 422:
		result := NewGetAllFoodItemsUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAllFoodItemsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAllFoodItemsOK creates a GetAllFoodItemsOK with default headers values
func NewGetAllFoodItemsOK() *GetAllFoodItemsOK {
	return &GetAllFoodItemsOK{}
}

/*GetAllFoodItemsOK handles this case with default header values.

A list of food items
*/
type GetAllFoodItemsOK struct {
	Payload []*models.FoodItem
}

func (o *GetAllFoodItemsOK) Error() string {
	return fmt.Sprintf("[GET /fooditem][%d] getAllFoodItemsOK  %+v", 200, o.Payload)
}

func (o *GetAllFoodItemsOK) GetPayload() []*models.FoodItem {
	return o.Payload
}

func (o *GetAllFoodItemsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAllFoodItemsUnprocessableEntity creates a GetAllFoodItemsUnprocessableEntity with default headers values
func NewGetAllFoodItemsUnprocessableEntity() *GetAllFoodItemsUnprocessableEntity {
	return &GetAllFoodItemsUnprocessableEntity{}
}

/*GetAllFoodItemsUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type GetAllFoodItemsUnprocessableEntity struct {
}

func (o *GetAllFoodItemsUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /fooditem][%d] getAllFoodItemsUnprocessableEntity ", 422)
}

func (o *GetAllFoodItemsUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAllFoodItemsInternalServerError creates a GetAllFoodItemsInternalServerError with default headers values
func NewGetAllFoodItemsInternalServerError() *GetAllFoodItemsInternalServerError {
	return &GetAllFoodItemsInternalServerError{}
}

/*GetAllFoodItemsInternalServerError handles this case with default header values.

Internal Server Error
*/
type GetAllFoodItemsInternalServerError struct {
}

func (o *GetAllFoodItemsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /fooditem][%d] getAllFoodItemsInternalServerError ", 500)
}

func (o *GetAllFoodItemsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
