// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CarbLevel CarbLevel is a numeric rank representation of the carbohydrates present in the food item
// The higher the level, the more carbohydrates the item has.
//
// swagger:model CarbLevel
type CarbLevel struct {

	// The description is a string describing the level, this will be either low, moderate, or high
	Description string `json:"description,omitempty"`

	// The id represents the carb level id: 1 = low, 2 = moderate, 3 = high in carbs
	// Required: true
	// Minimum: 1
	ID *uint8 `json:"id"`
}

// Validate validates this carb level
func (m *CarbLevel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CarbLevel) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.MinimumInt("id", "body", int64(*m.ID), 1, false); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CarbLevel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CarbLevel) UnmarshalBinary(b []byte) error {
	var res CarbLevel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
